import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Users table
  users: defineTable({
    // Clerk auth
    email: v.string(),
    tokenIdentifier: v.string(), // Clerk user ID for auth
    name: v.string(),
    imageUrl: v.optional(v.string()),

    // Onboarding
    hasCompletedOnboarding: v.boolean(),

    // Attendee preferences (from onboarding)
    location: v.optional(
      v.object({
        city: v.string(),
        state: v.optional(v.string()), // Added state field
        country: v.string(),
      })
    ),
    interests: v.optional(v.array(v.string())), // Min 3 categories

    // Organizer tracking (User Subscription)
    freeEventsCreated: v.number(), // Track free event limit (1 free)

    // Stripe Connect (for organizer payouts)
    stripeConnectId: v.optional(v.string()),
    stripeOnboardingComplete: v.optional(v.boolean()),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_token", ["tokenIdentifier"]), // Primary auth lookup

  // Events table
  events: defineTable({
    title: v.string(),
    description: v.string(),
    slug: v.string(),

    // Organizer
    organizerId: v.id("users"),
    organizerName: v.string(),

    // Event details
    category: v.string(),
    tags: v.array(v.string()),

    // Date & Time
    startDate: v.number(),
    endDate: v.number(),
    timezone: v.string(),

    // Location
    locationType: v.union(v.literal("physical"), v.literal("online")),
    venue: v.optional(v.string()),
    address: v.optional(v.string()),
    city: v.string(),
    state: v.optional(v.string()), // Added state field
    country: v.string(),

    // Capacity & Ticketing
    capacity: v.number(),
    ticketType: v.union(v.literal("free"), v.literal("paid")),
    ticketPrice: v.optional(v.number()), // Paid at event offline
    registrationCount: v.number(),

    // AI Intelligence & Predictions
    predictedDemand: v.optional(v.number()), // AI demand score (0-100)
    predictedRevenue: v.optional(v.number()), // Forecasted revenue

    // Dynamic Pricing
    dynamicPricingEnabled: v.optional(v.boolean()),
    basePriceMin: v.optional(v.number()), // Minimum price floor
    basePriceMax: v.optional(v.number()), // Maximum price ceiling
    currentPrice: v.optional(v.number()), // Real-time dynamic price

    // Analytics
    views: v.optional(v.number()), // Page view counter
    conversionRate: v.optional(v.number()), // Views to registrations ratio

    // Customization
    coverImage: v.optional(v.string()),
    themeColor: v.optional(v.string()),

    // Timestamps
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_organizer", ["organizerId"])
    .index("by_category", ["category"])
    .index("by_start_date", ["startDate"])
    .index("by_slug", ["slug"])
    .searchIndex("search_title", { searchField: "title" }),

  // Registrations/Tickets
  registrations: defineTable({
    eventId: v.id("events"),
    userId: v.id("users"),

    // Attendee info
    attendeeName: v.string(),
    attendeeEmail: v.string(),

    // QR Code for entry
    qrCode: v.string(), // Unique ID for QR

    // Check-in
    checkedIn: v.boolean(),
    checkedInAt: v.optional(v.number()),

    // Status
    status: v.union(v.literal("confirmed"), v.literal("cancelled")),

    registeredAt: v.number(),
  })
    .index("by_event", ["eventId"])
    .index("by_user", ["userId"])
    .index("by_event_user", ["eventId", "userId"])
    .index("by_qr_code", ["qrCode"]),

  // Price History (for dynamic pricing analytics)
  priceHistory: defineTable({
    eventId: v.id("events"),
    price: v.number(),
    reason: v.string(), // e.g., "surge_pricing", "early_bird", "manual_update"
    registrationCount: v.number(), // Snapshot of registrations at time of change
    timestamp: v.number(),
  }).index("by_event", ["eventId"]),

  // Event Analytics (daily snapshots)
  eventAnalytics: defineTable({
    eventId: v.id("events"),
    date: v.string(), // YYYY-MM-DD format
    views: v.number(),
    registrations: v.number(),
    revenue: v.number(),
    timestamp: v.number(),
  })
    .index("by_event", ["eventId"])
    .index("by_event_date", ["eventId", "date"]),
  // Payments (SSL Commerz Mock)
  payments: defineTable({
    eventId: v.id("events"),
    registrationId: v.id("registrations"),
    organizerId: v.id("users"), // For easy queries

    // Financials (in BDT)
    amount: v.number(),          // Total paid by user

    // SSL Commerz Metadata
    sslTranId: v.string(),       // Unique transaction ID generated by us
    sslValId: v.optional(v.string()), // Validation ID from SSL Commerz
    gatewayStatus: v.string(), // "VALID", "FAILED", "CANCELLED", "PENDING"

    // Status
    status: v.union(
      v.literal("pending"),
      v.literal("completed"),
      v.literal("failed"),
      v.literal("refunded"),
    ),

    createdAt: v.number(),
  })
    .index("by_event", ["eventId"])
    .index("by_organizer", ["organizerId"])
    .index("by_tran_id", ["sslTranId"]),
});
